[package]
name = "weibo-desktop"
version = "1.0.0"
description = "Unofficial Lightweight Weibo Desktop App"
authors = ["K4RLT"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
